<?php
/** @package Michat::Model::DAO */

/** import supporting libraries */
require_once("verysimple/Phreeze/Phreezable.php");
require_once("FriendshipMap.php");

/**
 * FriendshipDAO provides object-oriented access to the friendship table.  This
 * class is automatically generated by ClassBuilder.
 *
 * WARNING: THIS IS AN AUTO-GENERATED FILE
 *
 * This file should generally not be edited by hand except in special circumstances.
 * Add any custom business logic to the Model class which is extended from this DAO class.
 * Leaving this file alone will allow easy re-generation of all DAOs in the event of schema changes
 *
 * @package Michat::Model::DAO
 * @author ClassBuilder
 * @version 1.0
 */
class FriendshipDAO extends Phreezable
{
	/** @var int */
	public $Id;

	/** @var int */
	public $SourceUserId;

	/** @var int */
	public $TargetUserId;

	/** @var int */
	public $Accepted;

	/** @var int */
	public $Mutual;


	/**
	 * Returns the foreign object based on the value of SourceUserId
	 * @return User
	 */
	public function GetSourceUser()
	{
		return $this->_phreezer->GetManyToOne($this, "f_FK_sourceUser");
	}

	/**
	 * Returns the foreign object based on the value of TargetUserId
	 * @return User
	 */
	public function GetTargetUser()
	{
		return $this->_phreezer->GetManyToOne($this, "f_FK_targetUser");
	}


}
?>