<?php
/** @package Michat::Model::DAO */

/** import supporting libraries */
require_once("verysimple/Phreeze/Phreezable.php");
require_once("MessageMap.php");

/**
 * MessageDAO provides object-oriented access to the message table.  This
 * class is automatically generated by ClassBuilder.
 *
 * WARNING: THIS IS AN AUTO-GENERATED FILE
 *
 * This file should generally not be edited by hand except in special circumstances.
 * Add any custom business logic to the Model class which is extended from this DAO class.
 * Leaving this file alone will allow easy re-generation of all DAOs in the event of schema changes
 *
 * @package Michat::Model::DAO
 * @author ClassBuilder
 * @version 1.0
 */
class MessageDAO extends Phreezable
{
	/** @var int */
	public $Id;

	/** @var string */
	public $Contents;

	/** @var date */
	public $TimeStamp;

	/** @var int */
	public $SourceUserId;

	/** @var int */
	public $SourceTargetId; //TargetUserId

	/** @var int */
	public $Read;


	/**
	 * Returns the foreign object based on the value of SourceUserId
	 * @return User
	 */
	public function GetSourceUser()
	{
		return $this->_phreezer->GetManyToOne($this, "m_FK_source");
	}

	/**
	 * Returns the foreign object based on the value of SourceTargetId
	 * @return User
	 */
	public function GetSourceTargetUser()
	{
		return $this->_phreezer->GetManyToOne($this, "m_FK_target");
	}


}
?>