<?php
/** @package Michat::Model::DAO */

/** import supporting libraries */
require_once("verysimple/Phreeze/Phreezable.php");
require_once("UserMap.php");

/**
 * UserDAO provides object-oriented access to the user table.  This
 * class is automatically generated by ClassBuilder.
 *
 * WARNING: THIS IS AN AUTO-GENERATED FILE
 *
 * This file should generally not be edited by hand except in special circumstances.
 * Add any custom business logic to the Model class which is extended from this DAO class.
 * Leaving this file alone will allow easy re-generation of all DAOs in the event of schema changes
 *
 * @package Michat::Model::DAO
 * @author ClassBuilder
 * @version 1.0
 */
class UserDAO extends Phreezable
{
	/** @var int */
	public $Id;

	/** @var string */
	public $Username;

	/** @var string */
	public $Password;

	/** @var date */
	public $LastSeen;

	/** @var int */
	public $Connected;

	/** @var int */
	public $PublicProfile;

	/** @var string */
	public $PublicKey;


	/**
	 * Returns a dataset of Friendship objects with matching SourceUserId
	 * @param Criteria
	 * @return DataSet
	 */
	public function GetSourceFriendships($criteria = null)
	{
		return $this->_phreezer->GetOneToMany($this, "f_FK_sourceUser", $criteria);
	}

	/**
	 * Returns a dataset of Friendship objects with matching TargetUserId
	 * @param Criteria
	 * @return DataSet
	 */
	public function GetTargetFriendships($criteria = null)
	{
		return $this->_phreezer->GetOneToMany($this, "f_FK_targetUser", $criteria);
	}

	/**
	 * Returns a dataset of Message objects with matching SourceUserId
	 * @param Criteria
	 * @return DataSet
	 */
	public function GetSourceMessages($criteria = null)
	{
		return $this->_phreezer->GetOneToMany($this, "m_FK_source", $criteria);
	}

	/**
	 * Returns a dataset of Message objects with matching SourceTargetId
	 * @param Criteria
	 * @return DataSet
	 */
	public function GetSourceTargetMessages($criteria = null)
	{
		return $this->_phreezer->GetOneToMany($this, "m_FK_target", $criteria);
	}


}
?>